//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /media/glitch/ExtraWorld/repos/ModularSkillScripts repos/ModularSkillScripts/Grammars/ModsaLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ModsaLang {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ModsaLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IModsaLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ModsaLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ModsaLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableEx([NotNull] ModsaLangParser.VariableExContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SetModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetModvalEx([NotNull] ModsaLangParser.SetModvalExContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumberEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberEx([NotNull] ModsaLangParser.NumberExContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CircleEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCircleEx([NotNull] ModsaLangParser.CircleExContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionEx([NotNull] ModsaLangParser.FunctionExContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MathEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathEx([NotNull] ModsaLangParser.MathExContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModvalEx([NotNull] ModsaLangParser.ModvalExContext context);
}
} // namespace ModsaLang
