//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /media/glitch/ExtraWorld/repos/ModularSkillScripts repos/ModularSkillScripts/Grammars/ModsaLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ModsaLang {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IModsaLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ModsaLangBaseListener : IModsaLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ModsaLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ModsaLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ModsaLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ModsaLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableEx([NotNull] ModsaLangParser.VariableExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableEx([NotNull] ModsaLangParser.VariableExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SetModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetModvalEx([NotNull] ModsaLangParser.SetModvalExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SetModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetModvalEx([NotNull] ModsaLangParser.SetModvalExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberEx([NotNull] ModsaLangParser.NumberExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberEx([NotNull] ModsaLangParser.NumberExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CircleEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCircleEx([NotNull] ModsaLangParser.CircleExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CircleEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCircleEx([NotNull] ModsaLangParser.CircleExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionEx([NotNull] ModsaLangParser.FunctionExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionEx([NotNull] ModsaLangParser.FunctionExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MathEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathEx([NotNull] ModsaLangParser.MathExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MathEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathEx([NotNull] ModsaLangParser.MathExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModvalEx([NotNull] ModsaLangParser.ModvalExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModvalEx([NotNull] ModsaLangParser.ModvalExContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ModsaLang
