//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /media/glitch/ExtraWorld/repos/ModularSkillScripts repos/ModularSkillScripts/Grammars/ModsaLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ModsaLang {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ModsaLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IModsaLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ModsaLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ModsaLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ModsaLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ModsaLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableEx([NotNull] ModsaLangParser.VariableExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableEx([NotNull] ModsaLangParser.VariableExContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SetModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetModvalEx([NotNull] ModsaLangParser.SetModvalExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SetModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetModvalEx([NotNull] ModsaLangParser.SetModvalExContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberEx([NotNull] ModsaLangParser.NumberExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberEx([NotNull] ModsaLangParser.NumberExContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CircleEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCircleEx([NotNull] ModsaLangParser.CircleExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CircleEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCircleEx([NotNull] ModsaLangParser.CircleExContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionEx([NotNull] ModsaLangParser.FunctionExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionEx([NotNull] ModsaLangParser.FunctionExContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MathEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathEx([NotNull] ModsaLangParser.MathExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MathEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathEx([NotNull] ModsaLangParser.MathExContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModvalEx([NotNull] ModsaLangParser.ModvalExContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ModvalEx</c>
	/// labeled alternative in <see cref="ModsaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModvalEx([NotNull] ModsaLangParser.ModvalExContext context);
}
} // namespace ModsaLang
